### ISSUE TITLE
Using the wrong time zone

### ISSUE THREAD

**Issue by esamson** [flathub/com.microsoft.Teams#12]
Time stamps seem to be on US Pacific Time instead of the time zone set on my OS.

Workaround is to launch with something like `flatpak run --env=TZ=Asia/Manila com.microsoft.Teams`.

**Comment by Lctrs** [comment]
Hi.

May you test #13 and tells me if it fixes your issue please ?

**Comment by esamson** [comment]
Tried it and it works as expected.

**Comment by Lctrs** [comment]
Thank you for testing it. Should be available in 1-2 hours.

**Comment by esamson** [comment]
Thanks for the quick fix!
