### ISSUE TITLE
Unable to join meeting with link 

### ISSUE THREAD

**Issue by sschuhmann** [flathub/com.microsoft.Teams#14]
Currently I'm unable to join a web meeting by a link from an outlook calendar entry.

Chrome redirects the link to xdg-open, but teams seems not to be associated with the link. Is there any fix possible?

**Comment by Lctrs** [comment]
#15 possibly fixes it, but I'm not sure. Can you test it when the test build is done and tells me if it does please ?

**Comment by sschuhmann** [comment]
Sure! What is the best way to test a development flatpak? Can I install it with a different name?

**Comment by sschuhmann** [comment]
The PR fixes the issue! 
Thank your for the quick fix :)

**Comment by x80486** [comment]
I'm trying to do the same thing and it doesn't work so far. Would this work if the Web browser where the link is going to be opened from is running as a Flatpak? That's the only difference I can think of.

**Comment by maymage** [comment]
Hi all, 

I think this issue should been reopened. 

I'm using Firefox(Flatpak)+MS-Teams(Flatpak). 

Clicking on link of type 

https://teams.microsoft.com/l/meetup-join/19%3a6d688dcd04...

the Teams does not open the link.

**Comment by sschuhmann** [comment]
From the setting I would guess the problem originates from the flatpaked version of firefox. 

To verify, can you reproduce the error with the native installed version? 

If not, the issue should be reported in the Firefox bugtracker regarding teams connection and xgd-open

**Comment by maymage** [comment]
Hi, thanks for the quick replay..

So it's working now on firefox(flatpak), after I made it work on firefox-esr(apt). 

I'll retry on my PC at my office on Monday to check again.

**Comment by digitalethics** [comment]
Opening links was working at some point in the past. I've tried it today with the latest available flatpak and it didn't work.

**Comment by andypillip** [comment]
Same for me, version 1.4.00.13653 does not open the corresponding target.

Desktop wise everything seems fine, when Firefox opens the original link, Teams is receiving focus, its just not doing anything.
The exposed desktop file from Flatpak includes  

`MimeType=x-scheme-handler/msteams;`

Maybe Flatpak does not pass the URL correctly?

I remember this discussion on the Repo version of Teams as well, could it be relevant?
https://docs.microsoft.com/en-us/answers/questions/298724/open-teams-meeting-link-on-linux-doens39t-work.html

**Comment by Knusper** [comment]
OK.  This also broke for me recently, and the only change that I see that could be related is this here
https://github.com/ravomavain/com.microsoft.Teams/commit/f797a8893aacecd0ba741c1936ce273e6d15b619

If I understand the documentation on the link provided by @andypillip correctly, then the `"$@"` needs to be passed before the parameters?

**Comment by andypillip** [comment]
The flatpak call looks different, but passing `"$@"` before the parameters does the trick for me. Can anybody confirm?

/var/lib/flatpak/app/com.microsoft.Teams/x86_64/stable/[hash]/files/bin/teams
```bash
…
exec env TMPDIR="$XDG_CACHE_HOME" zypak-wrapper /app/extra/teams/teams "$@" --disable-namespace-sandbox --disable-setuid-sandbox
```

**Comment by Lctrs** [comment]
PR welcome. And also #67

**Comment by Knusper** [comment]
Ah, I was just about to file a PR myself... thanks
