### ISSUE TITLE
Teams is terminated sometimes

### ISSUE THREAD

**Issue by sschuhmann** [flathub/com.microsoft.Teams#17]
If I have the Teams window open in the background, the applications gets sometimes terminated.

This could be caused by the high memory usage of the flatpak application, but might also be a different problem. 

What is the best way to extract logs from the flatpak installation for debugging?

**Comment by Lctrs** [comment]
AFAIK, the only logs we can get from the app are the one outputed to the terminal when launching it with the CLI. 

With flatpak, it would be `flatpak run com.microsoft.Teams`

Will do some research to find if there is other forms of logs.

**Comment by sschuhmann** [comment]
I get this in the terminal while running Teams

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by Lctrs** [comment]
Yep noticed it. Since we're just a wrapper around the app and aren't related at all with Microsoft, it's unlikely that we can do something about it. You should contact them about your issue.

**Comment by Lctrs** [comment]
Could you try to reproduce your problem with the deb package ?

**Comment by sschuhmann** [comment]
I have started it via command line and it's working for several hours now. 
Could there be a problem with the launcher association?

**Comment by sschuhmann** [comment]
The same happens if I start it in the terminal.
I'll install the rpm in a vm to test it

**Comment by sschuhmann** [comment]
The error does not occur on my other notebook running the rpm package provided by microsoft.

**Comment by Lctrs** [comment]
Could you test with the just merged latest version once it's available ?

**Comment by sschuhmann** [comment]
I haven't encountered this error again, but will do more testing with the app minimized. I'll give another update soon.

Thank you for your work!

**Comment by Lctrs** [comment]
Oh I haven't done anything. Thanks to you for reporting bugs and testing new versions.

**Comment by Lctrs** [comment]
Considered as fixed.
