### ISSUE TITLE
The icon is now missing

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.microsoft.Teams#2]
![Captura de tela de 2019-12-20 18-20-37](https://user-images.githubusercontent.com/26097419/71293851-7b892800-2355-11ea-9df7-b688c5543c05.png)

**Comment by Lctrs** [comment]
Yeah. I couldn't find the icon on the web. Would it be okay to also download the deb package during build time to just extract the icon from it ? Or should I just commit it to the git repo ?

**Comment by bilelmoussaoui** [comment]
The app is not available from Flathub neither. Probably something not being installed correctly at build, might be the icon

**Comment by barthalion** [comment]
If it's unavailable online, add it to the git repository.
