### ISSUE TITLE
Crash when sharing screen when on Wayland

### ISSUE THREAD

**Issue by MightyCreak** [flathub/com.microsoft.Teams#23]
Hi!

Thanks for packaging this application, it's the main communication channel in our company.

I had to switch back to Xorg because sharing the screen when on Wayland is actually crashing the application (may not be the packaging fault though, but before opening a ticket to Microsoft, I wanted to ask here first).

Cheers!

**Comment by Lctrs** [comment]
AFAIK, sharing screens does not work with Wayland. With any apps.

**Comment by bilelmoussaoui** [comment]
> AFAIK, sharing screens does not work with Wayland. With any apps.

with any electron app, yes.

**Comment by Lctrs** [comment]
Thanks for the clarification @bilelmoussaoui

**Comment by TingPing** [comment]
Its upstreams bug.

**Comment by psarraf** [comment]
Screen sharing works in Wayland with the web version of Teams in Chromium 81. I was only able to share the entire desktop or a chromium tab or a chromium app, no other applications. In any case, screen sharing appears to work better in Chromium than as an Electron app.

**Comment by qike-ms** [comment]
I had to switch to X11 for sharing to work perfectly.
