### ISSUE TITLE
Cannot inhibit screen blanking

### ISSUE THREAD

**Issue by taaem** [flathub/com.microsoft.Teams#24]
In the flatpak Microsoft Teams cannot inhibit screen blanking, when in a video conference.
This is probably due to some dbus access which is not exposed.

**Comment by taaem** [comment]
The Skype Flatpak is using:
`        "--system-talk-name=org.freedesktop.login1",`
So probably teams is using the same method for screen inhibiting, which means this line has to be added to the flatpak

**Comment by Lctrs** [comment]
Hi. May you test #25 and tells me if it fixes your issue ? BTW, thank you for finding a potential fix.

**Comment by taaem** [comment]
I tested it and sadly it doesn't work, Teams is probably using a different dbus API, but that needs to be researched.

**Comment by Lctrs** [comment]
Have you tested that inhibiting screen blanking works in the deb version ?

I'm not using teams anymore so I can't test this myself.

**Comment by taaem** [comment]
Okay, I found out which dbus interface their using, you need to add:
```
--talk-name=org.gnome.SessionManager
```
At least it worked when I overrode access to that in my local installation

**Comment by Lctrs** [comment]
Thanks for tracking this down @taaem !

The fix has been merged, should be available soon.
