### ISSUE TITLE
Teams flatpak doesn't seem to use proxy.

### ISSUE THREAD

**Issue by tdaven** [flathub/com.microsoft.Teams#27]
I am unable to connect using the flatpak version when behind a corporate proxy.  The non-flatpak version connects fine with the proxy configuration.  If I remove the corporate proxy config the non-flatpak version fails to connect in what appears to be the same failure.  

A proxy is configured in the gnome proxy settings and environment variables are set for http_proxy and the other usual variants.

Looking at Wireshark I see connection attempts to Microsoft azure servers that are clearly skipping the proxy and trying to connect directly.

This is on Fedora 32 though the same issue occurred with 31.

**Comment by Lctrs** [comment]
Looks like flatpak isn't following `http_proxy` and other variants to the sandbox.

What's the output of the second command when you run the following ones in the terminal ?

1. `flatpak run --command=sh com.microsoft.Teams`
2. `env`

Can you try the following command and tells me if it fixes your issue ?

```sh
$ flatpak run --env=http_proxy=$http_proxy --env=HTTP_PROXY=$HTTP_PROXY --env=https_proxy=$https_proxy --env=HTTPS_PROXY=$HTTPS_proxy com.microsoft.Teams
```

If it works, you can make the changes permanents with : 

```sh
$ flatpak override --env=http_proxy=$http_proxy --env=HTTP_PROXY=$HTTP_PROXY --env=https_proxy=$https_proxy --env=HTTPS_PROXY=$HTTPS_proxy com.microsoft.Teams
```

**Comment by tdaven** [comment]
I see the appropriate http variables set when I run env and manually
setting them doesn't make any difference.

**Comment by tdaven** [comment]
I have found the issue is the proxy settings from the desktop are not getting propagated to the sandbox environment.  Running "gsettings list-recursively org.gnome.system.proxy" shows the flatpak app doesn't see any proxy config while the host environment shoes the desktop settings.

Setting the same settings manually with gsettings in the shell and launching teams makes it work as intended.

**Comment by Lctrs** [comment]
Great ! Thanks for finding this. I'm closing this issue.
