### ISSUE TITLE
Crashes on copy and paste a hyperlink

### ISSUE THREAD

**Issue by sschuhmann** [flathub/com.microsoft.Teams#31]
While copying a hyperlink teams gets unresponsive and does not recover from this state

**Comment by Lctrs** [comment]
Hi @sschuhmann and thank you for reporting this.

Sadly, I don't use Teams myself anymore and I won't be able to debug things.

**Comment by Lctrs** [comment]
Could you test with the just merged latest version once it's available ?

**Comment by sschuhmann** [comment]
I haven't experienced this error since the last update.

**Comment by kelmes** [comment]
This seems to also be happening with the current version.
