### ISSUE TITLE
Are any of the XDG user directory permissions necessary?

### ISSUE THREAD

**Issue by a-vrma** [flathub/com.microsoft.Teams#33]
If you want to attach a file you can open the file picker, which bypasses permissions. Is there any other reason to have XDG user directory permissions?

**Comment by a-vrma** [comment]
Except for download obviously

**Comment by evilSwanson** [comment]
I don't think so. I have been using it for months without any problems and have only allowed access to xdg-download (for downloads).

**Comment by Lctrs** [comment]
Feel free to submit a PR then.
