### ISSUE TITLE
Crash when trying to share screen on wayland

### ISSUE THREAD

**Issue by greenfoo** [flathub/com.microsoft.Teams#35]
The issue has also been reported here: https://github.com/electron/electron/issues/23063

It looks like Electron needs to be built with `RTC_USE_PIPEWIRE=true` in order to fix this issue.

I don't know who is in charge of building Electron when using flatpak. Is it part of the flatpak environment or does it come with the app itself? In the later case, where should we open a new ticket? Maybe directly to Microsoft?

Thanks.

**Comment by Lctrs** [comment]
I do believe this should be reported to Microsoft.

**Comment by Lctrs** [comment]
Does it still happen with the latest update ?

**Comment by bkhl** [comment]
I tried this with the latest update and:

* I can share PowerPoint presentations without crashing.
* The option to share the screen is not presented.

Maybe Microsoft fixed the crash by disabling the option to share the screen in Wayland?

**Comment by FilBot3** [comment]
Shouldn't this:
* https://github.com/flathub/com.microsoft.Teams/blob/master/com.microsoft.Teams.json#L16

Also include the `--socket=wayland' then `--socket=fallback-x11' ?
