### ISSUE TITLE
Can only upload from Downloads folder. 

### ISSUE THREAD

**Issue by qasim83** [flathub/com.microsoft.Teams#38]
When I'm trying to upload a file, it only gives the option to browse to ~/Download folder. No other folders in the home directory are visible. 
![teams error](https://user-images.githubusercontent.com/59982512/94681390-46195e00-031b-11eb-9f40-0f49c20764cb.png)

**Comment by sp1ritCS** [comment]
Change the permissions from com.microsoft.Teams using flatseal
