### ISSUE TITLE
Teams missing from Flathub search

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.microsoft.Teams#4]
If you search for Teams, it doesn't show up on the site:
https://flathub.org/apps/search/teams

Seems to be related to #2 because the icon is still missing for when searching for it in the GNOME Software Center.

![Screenshot from 2019-12-30 23-30-49](https://user-images.githubusercontent.com/33983090/71603299-7ea5c480-2b5c-11ea-8a8b-60648ab764e8.png)

**Comment by Eonfge** [comment]
@bilelmoussaoui I recalled we had an issue like this before because of a `<launchable/>` metadata reference, could that be related?

**Comment by TingPing** [comment]
The problem is probably that your appstream file references a desktop file but that desktop file isn't shipped in the package.
