### ISSUE TITLE
Notifications on Window managers

### ISSUE THREAD

**Issue by ispanos** [flathub/com.microsoft.Teams#40]
On tilling window managers notifications start as a new tiled window, instead of a floating notification on the bottom right side.
I use `dunst` as my notification manager, but Teams uses it's own system. If Teams is the only window, maximized, on the workspace and a new notification come up, the window gets resized to half width and the notification takes the other half of the screen. I think that it happens only when teams isn't the focused window.

```
$ xprop
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY
_NET_WM_DESKTOP(CARDINAL) = 2
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 21295833
WM_NAME(UTF8_STRING) = "Microsoft Teams Notification"
_NET_WM_NAME(UTF8_STRING) = "Microsoft Teams Notification"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1612, 990
		program specified minimum size: 300 by 164
		program specified maximum size: 300 by 164
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "microsoft teams - preview", "Microsoft Teams - Preview"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION
_NET_WM_PID(CARDINAL) = 2
WM_LOCALE_NAME(STRING) = "C.UTF-8"
WM_CLIENT_MACHINE(STRING) = "killua"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

Edit: I'm using i3wm on Pop!_Os

**Comment by Lctrs** [comment]
I think this would requires something like https://github.com/dscharrer/steamwm to fix this. Sadly, I don't have the time (nor the right setup, I'm on Gnome) to implement something like this. If you can...

**Comment by Lctrs** [comment]
This being said, if you can reproduce the issue with the official `.deb` package, it's on microsoft side. If not, it's for me, but you shouldn't expect a quick fix (as per my answer above).

**Comment by ispanos** [comment]
It's fixed.
