### ISSUE TITLE
open .docx within Teams shows black screen

### ISSUE THREAD

**Issue by saknl** [flathub/com.microsoft.Teams#42]
When I open a .docx document with the integrated Office, it just works for a couple of seconds and then shows a black screen.
Starting Teams from terminal with `flatpak run com.microsoft.Teams` gives this output everytime the black screen appears: `../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230`
I'm using version 1.3.00.25560 on Fedora 33.

**Comment by Lctrs** [comment]
Could you test #43 ?

**Comment by saknl** [comment]
> Could you test #43 ?

Sorry, I didn't see your reply earlier and now the test build isn't online anymore. Trying to install it give this output: `Can't load uri https://dl.flathub.org/build-repo/31295/com.microsoft.Teams.flatpakref: Server returned status 404: Not Found`

**Comment by Lctrs** [comment]
Try `flatpak install https://dl.flathub.org/build-repo/31813/com.microsoft.Teams.flatpakref`

**Comment by saknl** [comment]
Thank you! Unfortunately the problem still persists in the test build. Here is the full output. Maybe that helps to find the problem. 

`flatpak run com.microsoft.Teams 
Overriding TZ to Europe/Amsterdam
Gtk-Message: 16:05:36.886: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:05:36.886: Failed to load module "pk-gtk-module"
Gtk-Message: 16:05:36.887: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:05:36.887: Failed to load module "pk-gtk-module"
(node:2) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at /app/extra/teams/resources/app.asar/node_modules/ipc-monitor/renderer/dom-observables.js:31:5
    at new Promise (<anonymous>)
    at Object.<anonymous> (/app/extra/teams/resources/app.asar/node_modules/ipc-monitor/renderer/dom-observables.js:30:30)
    at Object.<anonymous> (/app/extra/teams/resources/app.asar/node_modules/ipc-monitor/renderer/dom-observables.js:62:3)
    at Module._compile (/app/extra/teams/resources/app.asar/external/v8-compile-cache/v8-compile-cache.js:192:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added. Use emitter.setMaxListeners() to increase limit
(node:2) UnhandledPromiseRejectionWarning: undefined
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added. Use emitter.setMaxListeners() to increase limit
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
`

**Comment by Lctrs** [comment]
Friendly ping @refi64. Could this be caused by zypak ?

**Comment by refi64** [comment]
This was a [fixed bug in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1025739) on newer glibc versions, so MS just needs to update their Electron version. Best I could do is try and hack around it, but I'm not sure how doable it would be.

**Comment by Lctrs** [comment]
Thanks for your input @refi64 ! 

@saknl Does the issue still occur with latest update released 3 days ago ?

**Comment by saknl** [comment]
I can confirm that it was fixed with the new version 1.3.00.30857.

Electron was updated from version 4.2.12 to 8.5.2 with the latest Teams update.

Thank you for your help!
