### ISSUE TITLE
Teams not detecting camera or microphone

### ISSUE THREAD

**Issue by WoosterUK** [flathub/com.microsoft.Teams#44]
__OS__: Linux Mint 20

__Kernel version__: Linux 5.4.0-54-generic x86_64

__Teams version__: 1.3.00.25560

__Other relevant information__: I have v4l2loopback-dkms installed through my package manager, and generating a loopback device that is designed for use with OBS Studio to stream into virtual classrooms. I have two webcams attached plus an additional microphone, all by USB. guvcview detects both of the real webcams plus the loopback device.

__What happens__: I load Teams and (much of the time) I don't see an option to place a video call, reason "No available camera found". If I go to device settings, Teams does not find anything audiovisual: no camera, no microphone, no speakers. It is therefore impossible to participate in any calls. Teams seems to be particularly bad at finding my AV equipment on a second or subsequent loading of Teams; the first time up it's more reliable.

__What I have tried__: As indicated above, sometimes restarting the machine appears to help, although this morning the first loading of Teams exhibited the problem. I am not typically loading Teams alongside anything else that is trying to access the webcams as I know that different pieces of software can block each other from webcam access.

I have also tried running Teams from the command line. There was no obvious error message that related to webcams etc, but I'm happy to try to run it with different parameters / debugging tools if given instruction on what to do, and report the output.

**Comment by Lctrs** [comment]
Can you reproduce the issue with the official `.deb` package ? If yes, you should report the problem directly to Microsoft.

**Comment by WoosterUK** [comment]
Yes, apparently I can. Thanks, will try to work out how to report to MS.

**Comment by WoosterUK** [comment]
In case any Googlers ever find this, I subsequently discovered that this is the fix: https://docs.microsoft.com/en-us/answers/questions/3015/microphone-for-teams-on-linux-not-working.html?childToView=152753#comment-152753 . Add all users wanting Teams to the audio and video groups (or possibly pulse and video; I did all three to be on the safe side).
