### ISSUE TITLE
Teams does not save password

### ISSUE THREAD

**Issue by sp1ritCS** [flathub/com.microsoft.Teams#47]
I have to reenter the password of my account every time I restart teams.

**Comment by jacobzimmermann** [comment]
+1

**Comment by Lctrs** [comment]
Might be related to https://github.com/flatpak/xdg-desktop-portal/issues/507

**Comment by Lctrs** [comment]
Could you test #48 ?

**Comment by sp1ritCS** [comment]
This seems to work, even tho I can't find the correct entry with secret-tool or gnome seahorse

**Comment by Lctrs** [comment]
Thanks for the feedback. I think that's because this version doesn't store credentials on the host.

I'll merge this though, and monitor upstream bug for a fix.

**Comment by pha-nguyen** [comment]
Hi, I faced this problem in the most recent version 1.4.00.26453, any suggestions?

**Comment by Lctrs** [comment]
@FakeShemp You may try building the latest `libsecret` version with `-gcrypt=false` build option. You can take the recipe from shared-modules as a base.
