### ISSUE TITLE
Downloading files doesn't work

### ISSUE THREAD

**Issue by mcepl** [flathub/com.microsoft.Teams#52]
(and the same is true for `com.microsoft.Skype` as well)

When I go to download a file from Teams (or when I try to download a file send to me in a chat), Teams pretends it downloaded it, it actually even show it in “Downloaded Files” folder inside of teams, but the file is nowhere to be found on whole drive (even when running `find / -name <filename>` as root).

It certainly isn’t in the `~/Downloads` folder, where I would expect it to be.

Using stable package 1.3.00.30857 from flathub.

Something broken by #34, perhaps?

**Comment by mcepl** [comment]
Aaaah, directory `~/Downloads` must exist **BEFORE** Teams are started. Couldn't we get some kind of warning or something?

**Comment by Lctrs** [comment]
Should be reported directly to Microsoft.

**Comment by mcepl** [comment]
a) I thought that this repo is maintained by them,
b) you would be so kind and do it for me, right?

**Comment by Lctrs** [comment]
> b) you would be so kind and do it for me, right?

No.
