### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by Lctrs** [flathub/com.microsoft.Teams#67]
Hi everyone !

I'm not using Teams anymore for over a year now, and issues are stacking up since I can't try to reproduce them nor have the motivation to try to fix things frankly.

So I guess it's time to give the keys to another person (or more) who is (are) ready to take over the maintenance of this package.

ping @barthalion @bilelmoussaoui @nedrichards

**Comment by barthalion** [comment]
I'll be keeping an eye on pull requests/issues.

**Comment by Lctrs** [comment]
Since no one has stepped up yet, I guess there is no interest in having a flatpaked Teams. So I'm giving a one week notice before I'm EOL'd this project.

**Comment by Knusper** [comment]
There is definitely interest on my side on having teams via flatpak, but I am not in the situation where I can take up the job as maintaining the flatpak.  :(

**Comment by barthalion** [comment]
Sent an invite.

**Comment by Lctrs** [comment]
@FakeShemp Thank you very much for stepping in. Don't hesitate to ping me if you have any question.
