### ISSUE TITLE
Disconnect authentication provider

### ISSUE THREAD

**Issue by digitalethics** [flathub/com.microsoft.Teams#68]
I've previously used Okta to connect to my company resources, however, I now intend to use the Teams flatpak on this particular laptop without Okta. Is there a possibility to reset the Flatpak to not always autostart the Okta login screen? Uninstalling and reinstalling the flatpak didn't work in this case. Many thanks!

**Comment by Lctrs** [comment]
`$  flatpak run com.microsoft.Teams --reset` to run Teams with a fresh install and settings.
