### ISSUE TITLE
shared cannot viewed

### ISSUE THREAD

**Issue by Saulo0** [flathub/com.microsoft.Teams#69]
I did join at an conference with 19 participants, but only me can not viewed the presentation shared for the speaker. Earlier I disabled video of VLC Player to listen to some musics of Youtube. I did try to reinstall the Teams, but the issue did still, then I clean the directory "home/.var/app/com.microsoft.Teams" and do reinstall again. Looks like it worked when I did test with two devices but I going to confirm if really work at next conference.

**Comment by p-fruck** [comment]
I can confirm the behavior, but in my case the issue also occurs when having a meeting with only two persons or a direct call (two persons, again).  Since it has worked like a week ago and no update has been installed since then, is this due to a server-side change?

**Comment by bergmannf** [comment]
I also have the same issue, I also tried running it in the chromium browser (`chromium-freeworld` on Fedora, so I have all the codecs installed) and even there it didn't work.

So I am not sure if this is related to the flatpak at all.

**Comment by avaiss** [comment]
Same problem here (debian 10). With the flatpak app and chromium too. It started on Friday.

Additionnally it seems that the app crashes when staying too long in a call where someone shares it screen.

In case it would be of any importance, I have 2560x1440p resolution, and i am using xorg, not wayland.

**Comment by mkatt** [comment]
Seems that it's something related to the `rect-overlay` binary and the new Teams version.

After a downgrade, the things are working:

```
sudo flatpak update --commit=254d23b8f87936f75cfe86c965febec7f1d05c134475d60572343db2baa2d1a6 com.microsoft.Teams
```

and if you want to stop flatpak from updating this version of teams to the latest broken (until it's resolved, at least), you can do:

```
sudo flatpak mask flathub com.microsoft.Teams
```
