### ISSUE TITLE
Linux Mint 20.2 Teams sharing and cam broken

### ISSUE THREAD

**Issue by SScheiper** [flathub/com.microsoft.Teams#71]
Hi!

Updated to the latest version of Kernel (Linux Mint 20.2; Cinnamon 5.0.5; Kernel 5.4.0-80-generic) and drivers recently and now Teams 1.4.00.13654 (64-bit) stopped working properly:
- Screen sharing not possible (empty screen)
- Shared Screens are not shown, just a blank screen with Icon of the sharing user stays on the screen
- Webcam stopped working (Cam is identified as Full-HD, works with other apps properly), enabling it indicates properly that the cam is in use but the screen stays black. Changing configuration just lets the indicator blink for one time and shows a black screen as well
- Any changes by re-installing packages from the last few updates or even going back with Timeshift, do not change any behavior

What could possibly solve this problem?

Thanks!

-Stefan

**Comment by mkatt** [comment]
@SScheiper , please look at https://github.com/flathub/com.microsoft.Teams/issues/69#issuecomment-892586184
