### ISSUE TITLE
Open teams meeting link on linux doesn't work

### ISSUE THREAD

**Issue by marciosr** [flathub/com.microsoft.Teams#75]
Trying to open a meeting link doesn't work like was told on that link:

https://docs.microsoft.com/en-us/answers/questions/298724/open-teams-meeting-link-on-linux-doens39t-work.html

To fix, just need to change de "exec" line of "tems" executable script 
from:
``
exec env TMPDIR="$XDG_CACHE_HOME" zypak-wrapper /app/extra/teams/teams --disable-namespace-sandbox --disable-setuid-sandbox "$@"
``
to:
``
exec env TMPDIR="$XDG_CACHE_HOME" zypak-wrapper /app/extra/teams/teams "$@" --disable-namespace-sandbox --disable-setuid-sandbox
``

**Comment by Lctrs** [comment]
This is done since yesterday. Just update the flatpak.
